apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  name: {{ .Values.app.name }}
  labels:
    io.kompose.service: {{ .Values.app.name }}
{{ include "ts-node-starter-chart.labels" . | indent 4 }}  
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Values.app.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: FACEBOOK_ID
              valueFrom:
                configMapKeyRef:
                  key: FACEBOOK_ID
                  name: ts-node-starter-starter-env
            - name: FACEBOOK_SECRET
              valueFrom:
                configMapKeyRef:
                  key: FACEBOOK_SECRET
                  name: ts-node-starter-starter-env
            - name: MONGODB_URI_LOCAL
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_URI_LOCAL
                  name: ts-node-starter-starter-env
            - name: SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  key: SESSION_SECRET
                  name: ts-node-starter-starter-env    
          imagePullPolicy: {{ .Values.image.pullPolicy }}    
          resources: {}
      restartPolicy: Always
status: {}
