version: 2.1
orbs:
  gcr: circleci/gcp-gcr@0.6.1
  gke: circleci/gcp-gke@0.1.0

jobs:
  test:
    working_directory: ~/typescript-node-starter
    docker:
      - image: circleci/node:10.15.3
      - image: mongo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run tests
          command: npm test

  build-and-push-image:
    working_directory: ~/typescript-node-starter
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: typescript-node-starter
          registry-url: gcr.io
      - gcr/push-image:
          image: typescript-node-starter
          registry-url: gcr.io

  deploy-to-staging:
    machine: true
    steps:
      - gke/install
      - gke/init
      - gke/rollout-image:
          deployment: typescript-starter-staging-cluster
          image: gcr.io/max-infrastructure/ts-node-starter:latest
          container: ts-node-starter

workflows:
  version: 2.1
  build-and-push-image:
    jobs:
      - test
      - build-and-push-image:
          requires:
            - test
      - deploy-to-staging:
          requires:
            - build-and-push-image
          filters:
            branches:
              only: ci/cd
