version: 2.1
orbs:
  gcr: circleci/gcp-gcr@0.6.1

jobs:
  test:
    working_directory: ~/typescript-node-starter
    docker:
      - image: circleci/node:10.15.3
      - image: mongo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run tests
          command: npm test

  build-and-push-image:
    working_directory: ~/typescript-node-starter
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: typescript-node-starter
          registry-url: gcr.io
      - gcr/push-image:
          image: typescript-node-starter
          registry-url: gcr.io

workflows:
  version: 2.1
  build-and-push-image:
    jobs:
      - test
      - build-and-push-image:
          requires:
            - test
          filters:
            branches:
              only: ci/cd
